server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:3308/flight_amenity
    username: postgres
    password: 1234

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


flight-amenity:
  amenity-url: http://127.0.0.1:3000/amenities


logstash:
  appender: LOGSTASH
  host: 127.0.0.1
  port: 3310









